// All user-facing copy lives here. EN + AR mirrored.
// Arabic uses Saudi Khaleeji-friendly phrasing.

type Dict = Record<string, string>;

const en: Dict = {
  // Nav
  'nav.players': 'For Players',
  'nav.organisers': 'For Organisers',
  'nav.referees': 'For Referees',
  'nav.features': 'Features',
  'nav.pricing': 'Pricing',
  'nav.download': 'Download',
  'nav.contact': 'Contact',
  'nav.menu': 'Menu',
  'nav.close': 'Close',
  'lang.toggle': 'العربية',
  'lang.aria': 'Switch language',

  // Footer
  'footer.tagline': 'Your pitch. Your rules.',
  'footer.company': 'Kickoff Technologies',
  'footer.rights': 'All rights reserved.',
  'footer.product': 'Product',
  'footer.legal': 'Legal',
  'footer.contactCol': 'Contact',
  'footer.privacy': 'Privacy Policy',
  'footer.terms': 'Terms of Service',
  'footer.support': 'support@kickoffsa.com',
  'footer.riyadh': 'Built in Riyadh, KSA.',

  // Home
  'home.hero.eyebrow': 'AMATEUR FOOTBALL · RIYADH',
  'home.hero.title': 'Your pitch. Your rules.',
  'home.hero.sub': 'Kickoff is the mobile-first platform for running and playing 8-a-side football tournaments in Saudi Arabia — teams, fixtures, results, all in one app.',
  'home.hero.cta.primary': 'Get notified at launch',
  'home.hero.cta.secondary': 'How it works',
  'home.hero.note': 'iOS and Android · English and العربية · Coming soon to the App Store and Google Play.',

  'home.strip.title': 'Three taps. One tournament.',
  'home.strip.1.title': 'Build your profile',
  'home.strip.1.body': 'Set your position, jersey number, and city. Sign in with Apple, Google, or email.',
  'home.strip.2.title': 'Create or join a team',
  'home.strip.2.body': 'Pick a crest, invite your squad with a join code, or jump into a public team.',
  'home.strip.3.title': 'Compete in tournaments',
  'home.strip.3.body': 'Register for an 8-team bracket, follow fixtures, watch the standings update.',

  'home.roles.title': 'Built for everyone on the pitch.',
  'home.roles.sub': 'Three roles. No admins, no spectators, no fluff.',
  'home.roles.player.title': 'Players',
  'home.roles.player.body': 'Browse open tournaments in your city, manage your team, and track your career stats.',
  'home.roles.player.cta': 'For players',
  'home.roles.organiser.title': 'Organisers',
  'home.roles.organiser.body': 'Spin up an 8-team tournament in three steps. Approve teams, enter results, manage suspensions.',
  'home.roles.organiser.cta': 'For organisers',
  'home.roles.referee.title': 'Referees',
  'home.roles.referee.body': 'See your assigned matches grouped by date. Submit the result in the same form organisers use.',
  'home.roles.referee.cta': 'For referees',

  'home.how.title': 'How a tournament runs on Kickoff.',
  'home.how.sub': 'Eight teams. Two groups of four. Semis. A final. The bracket fills itself.',
  'home.how.1.title': 'Create in three steps',
  'home.how.1.body': 'Name and city · venue, pitches, and dates · entry fee and review.',
  'home.how.2.title': 'Approve teams',
  'home.how.2.body': 'Captains register their squad. You decide who plays.',
  'home.how.3.title': 'Generate fixtures',
  'home.how.3.body': 'The server builds the bracket. No spreadsheets, no shuffling.',
  'home.how.4.title': 'Enter results',
  'home.how.4.body': 'You or your referee log scores, scorers, cards, and penalties.',
  'home.how.5.title': 'Bracket auto-advances',
  'home.how.5.body': 'Semi-finals fill in after the group stage. The final fills in after the semis.',

  'home.proof.title': 'Why teams pick Kickoff.',
  'home.proof.1': 'Full English and Arabic with RTL layout.',
  'home.proof.2': 'Sign in with Apple, Google, or email.',
  'home.proof.3': 'Run tournaments end-to-end without spreadsheets.',
  'home.proof.4': 'Built for amateur football in Saudi Arabia.',

  'home.cta.title': 'Ready to run your next tournament?',
  'home.cta.sub': "We're polishing the iOS and Android apps now. Drop your email and we'll let you know the moment they go live.",
  'home.cta.button': 'Get notified at launch',

  // For Players
  'players.eyebrow': 'FOR PLAYERS',
  'players.title': 'Find your squad. Find a tournament. Show up.',
  'players.sub': 'Kickoff puts amateur football in your pocket — your team, your fixtures, your stats.',
  'players.f.1.title': 'Build your profile',
  'players.f.1.body': 'Name, date of birth, position (GK, DEF, MID, FWD), jersey number, city, and a profile photo.',
  'players.f.2.title': 'Create or join a team',
  'players.f.2.body': 'Start your own squad with a crest and colours, or join with an invite link, join code, or public-team search.',
  'players.f.3.title': 'Captain tools',
  'players.f.3.body': 'Manage the roster, regenerate the join code, set co-captain, toggle public or private, and register for tournaments.',
  'players.f.4.title': 'Follow the bracket',
  'players.f.4.body': 'Group standings, upcoming fixtures, knockout bracket, and a champion banner when the dust settles.',
  'players.f.5.title': 'Career stats',
  'players.f.5.body': 'Matches played, goals, assists, yellow and red cards, tournaments played, tournaments won.',
  'players.f.6.title': 'Push notifications',
  'players.f.6.body': 'Invites, match reminders, and results — all delivered to your phone.',

  // For Organisers
  'organisers.eyebrow': 'FOR ORGANISERS',
  'organisers.title': 'Run an 8-team tournament without a spreadsheet in sight.',
  'organisers.sub': 'From registration to final whistle, Kickoff handles the structure so you can run the day.',
  'organisers.step.1.title': 'Step 1 — Identity',
  'organisers.step.1.body': 'Tournament name, city, squad size (6–11), public or private visibility, optional description and cover photo.',
  'organisers.step.2.title': 'Step 2 — Where and when',
  'organisers.step.2.body': 'Venue, list of pitches with a final field marked, allowed 30-minute time slots between 6am and 11:30pm, and the dates for the first match, semi-finals, and final.',
  'organisers.step.3.title': 'Step 3 — Money and review',
  'organisers.step.3.body': 'Entry fee in SAR (default 1,500), an auto-suggested registration deadline, and a final review.',
  'organisers.during.title': 'On match day',
  'organisers.during.1': 'Approve or reject team registrations as they arrive.',
  'organisers.during.2': 'Generate fixtures with one tap — the server builds the bracket.',
  'organisers.during.3': 'Open any match to enter the result, assign a referee, or reschedule.',
  'organisers.during.4': 'Log goals, assists, yellow and red cards, and penalty shootouts for knockout draws.',
  'organisers.during.5': 'Manage suspensions — 2 matches by default, or upgrade to tournament or indefinite bans.',
  'organisers.during.6': 'Run quick matches — friendly one-offs that use the same result form.',
  'organisers.payments.title': 'Payments and refunds',
  'organisers.payments.body': 'Entry fees are collected in SAR through Moyasar — Kickoff is not the merchant of record. If you cancel a tournament, Kickoff triggers refund attempts on all paid registrations. Any that fail enter a pending-refund state for you to reconcile.',

  // For Referees
  'referees.eyebrow': 'FOR REFEREES',
  'referees.title': 'Your matches. One screen. Submit and done.',
  'referees.sub': 'Kickoff gives referees a focused dashboard with everything you need on the day.',
  'referees.f.1.title': 'Today, this week, unscheduled',
  'referees.f.1.body': 'Assigned matches grouped by date — anything without a kickoff time floats to the top.',
  'referees.f.2.title': 'Open a match, submit a result',
  'referees.f.2.body': 'The same result form organisers use: home and away scores, goal scorers, optional assists, yellow and red cards, and penalty shootouts in knockouts.',
  'referees.f.3.title': 'Standings update live',
  'referees.f.3.body': 'When you submit, group standings and the knockout bracket update for everyone connected.',

  // Features
  'features.eyebrow': 'FEATURES',
  'features.title': 'Everything Kickoff actually does today.',
  'features.sub': 'A factual list — no roadmap fluff, no "coming soon" boxes.',
  'features.cat.tournaments': 'Tournaments',
  'features.cat.teams': 'Teams',
  'features.cat.matches': 'Matches and results',
  'features.cat.accounts': 'Accounts',
  'features.cat.platform': 'Platform',

  // Pricing
  'pricing.eyebrow': 'PRICING',
  'pricing.title': 'Free for players. Set your own fee as an organiser.',
  'pricing.sub': 'Kickoff itself is free to download and use. Organisers set the entry fee for each tournament they run.',
  'pricing.players.title': 'Players',
  'pricing.players.price': 'Free',
  'pricing.players.body': 'Download Kickoff, build your profile, join or create a team, and register for tournaments. No subscription, no in-app currency.',
  'pricing.players.bullet.1': 'Unlimited teams across roles',
  'pricing.players.bullet.2': 'Career stats and tournament history',
  'pricing.players.bullet.3': 'Push notifications for invites and matches',
  'pricing.organisers.title': 'Organisers',
  'pricing.organisers.price': 'You decide',
  'pricing.organisers.body': 'Set the entry fee in SAR when you create a tournament (default 1,500 SAR). Payments are processed in SAR through Moyasar — Kickoff is not the merchant of record for entry fees.',
  'pricing.organisers.bullet.1': '8-team brackets with auto-advancement',
  'pricing.organisers.bullet.2': 'Registration approvals and refund flow',
  'pricing.organisers.bullet.3': 'Result entry, suspensions, and quick matches',
  'pricing.note': 'Refunds are organiser-driven through Moyasar. Kickoff facilitates refund attempts on cancellations but does not guarantee them.',

  // Download
  'download.eyebrow': 'DOWNLOAD',
  'download.title': 'Coming soon to iOS and Android.',
  'download.sub': "We're putting the final polish on the apps before they hit the App Store and Google Play. Leave your email and we'll let you know the moment they go live.",
  'download.cta': 'Email us at support@kickoffsa.com',
  'download.ios.title': 'iOS',
  'download.ios.body': 'Apple App Store · coming soon',
  'download.android.title': 'Android',
  'download.android.body': 'Google Play · coming soon',

  // Contact
  'contact.eyebrow': 'CONTACT',
  'contact.title': "Let's talk football.",
  'contact.sub': 'Questions, feedback, or a tournament you want to run? Get in touch.',
  'contact.support.title': 'Support',
  'contact.support.body': 'For account help, payments, or anything else.',
  'contact.support.cta': 'support@kickoffsa.com',
  'contact.legal.title': 'Legal entity',
  'contact.legal.body': 'Kickoff Technologies · Kingdom of Saudi Arabia · Jurisdiction: courts of Riyadh.',

  // 404
  '404.title': 'Off the pitch.',
  '404.sub': "That page isn't here. Let's get you back to the action.",
  '404.cta': 'Back home',

  // Privacy / Terms (compact summary on-site)
  'privacy.eyebrow': 'PRIVACY',
  'privacy.title': 'Privacy Policy',
  'privacy.updated': 'Last updated: May 2026',
  'terms.eyebrow': 'TERMS',
  'terms.title': 'Terms of Service',
  'terms.updated': 'Last updated: May 2026',
};

const ar: Dict = {
  // Nav
  'nav.players': 'للاعبين',
  'nav.organisers': 'للمنظّمين',
  'nav.referees': 'للحكّام',
  'nav.features': 'المميزات',
  'nav.pricing': 'الأسعار',
  'nav.download': 'تحميل',
  'nav.contact': 'تواصل',
  'nav.menu': 'القائمة',
  'nav.close': 'إغلاق',
  'lang.toggle': 'English',
  'lang.aria': 'تغيير اللغة',

  // Footer
  'footer.tagline': 'ملعبك. قوانينك.',
  'footer.company': 'كيك أوف تكنولوجيز',
  'footer.rights': 'جميع الحقوق محفوظة.',
  'footer.product': 'المنتج',
  'footer.legal': 'القانوني',
  'footer.contactCol': 'تواصل',
  'footer.privacy': 'سياسة الخصوصية',
  'footer.terms': 'شروط الخدمة',
  'footer.support': 'support@kickoffsa.com',
  'footer.riyadh': 'صُنع في الرياض، المملكة العربية السعودية.',

  // Home
  'home.hero.eyebrow': 'كرة هوّاة · الرياض',
  'home.hero.title': 'ملعبك. قوانينك.',
  'home.hero.sub': 'كيك أوف منصّة من الجوال لتنظيم بطولات الكرة 8 ضد 8 في السعودية — فِرَق وجداول ونتائج، كلّها في تطبيق واحد.',
  'home.hero.cta.primary': 'بلّغوني عند الإطلاق',
  'home.hero.cta.secondary': 'كيف يشتغل التطبيق',
  'home.hero.note': 'لـ iOS و Android · عربي وإنجليزي · قريبًا على App Store و Google Play.',

  'home.strip.title': 'ثلاث ضغطات. بطولة كاملة.',
  'home.strip.1.title': 'سوّ ملفك الشخصي',
  'home.strip.1.body': 'حدّد مركزك ورقم قميصك ومدينتك. سجّل دخولك بـ Apple أو Google أو الإيميل.',
  'home.strip.2.title': 'كوّن فريق أو انضم لواحد',
  'home.strip.2.body': 'اختر شعار الفريق، ادعُ شِلّتك برمز الانضمام، أو انضم لفريق عام.',
  'home.strip.3.title': 'نافس في البطولات',
  'home.strip.3.body': 'سجّل في بطولة بثمانية فِرَق، تابع المباريات، وشوف الترتيب يتحدث مباشرة.',

  'home.roles.title': 'مصمّم لكلّ من في الملعب.',
  'home.roles.sub': 'ثلاثة أدوار. بدون أدمن، بدون مشاهدين، بدون حشو.',
  'home.roles.player.title': 'اللاعبون',
  'home.roles.player.body': 'تصفّح البطولات المفتوحة في مدينتك، أدِر فريقك، وتابع إحصائياتك.',
  'home.roles.player.cta': 'للاعبين',
  'home.roles.organiser.title': 'المنظّمون',
  'home.roles.organiser.body': 'أنشئ بطولة بثمانية فِرَق في ثلاث خطوات. اقبل الفِرَق، أدخل النتائج، وأدِر الإيقافات.',
  'home.roles.organiser.cta': 'للمنظّمين',
  'home.roles.referee.title': 'الحكّام',
  'home.roles.referee.body': 'شاهد مبارياتك مرتّبة بحسب التاريخ. أدخل النتيجة بنفس النموذج اللي يستخدمه المنظّم.',
  'home.roles.referee.cta': 'للحكّام',

  'home.how.title': 'كيف تشتغل البطولة على كيك أوف.',
  'home.how.sub': 'ثمانية فِرَق. مجموعتان من أربعة. نصف نهائي. نهائي. الجدول يتعبّى وحده.',
  'home.how.1.title': 'أنشئ في ثلاث خطوات',
  'home.how.1.body': 'الاسم والمدينة · الملعب والمواعيد · رسوم الاشتراك والمراجعة.',
  'home.how.2.title': 'اقبل الفِرَق',
  'home.how.2.body': 'كباتن الفِرَق يسجّلون. أنت تقرّر مين يلعب.',
  'home.how.3.title': 'ولّد الجدول',
  'home.how.3.body': 'السيرفر يبني البطولة. بدون جداول إكسل، بدون قرعة يدوية.',
  'home.how.4.title': 'أدخل النتائج',
  'home.how.4.body': 'أنت أو الحكم تسجّلون النتيجة والأهداف والإنذارات والضربات الترجيحية.',
  'home.how.5.title': 'الجدول يتقدّم تلقائيًا',
  'home.how.5.body': 'نصف النهائي يتعبّى بعد دور المجموعات، والنهائي يتعبّى بعد نصف النهائي.',

  'home.proof.title': 'ليش الفِرَق تختار كيك أوف.',
  'home.proof.1': 'دعم كامل للعربية والإنجليزية مع تنسيق RTL.',
  'home.proof.2': 'تسجيل دخول بـ Apple أو Google أو الإيميل.',
  'home.proof.3': 'إدارة بطولة كاملة بدون جداول إكسل.',
  'home.proof.4': 'مصمّم لكرة الهواة في السعودية.',

  'home.cta.title': 'جاهز تنظّم بطولتك القادمة؟',
  'home.cta.sub': 'نشتغل الحين على آخر اللمسات لتطبيقات iOS و Android. أرسل لنا إيميل ونبلّغك أوّل ما ينزل التطبيق.',
  'home.cta.button': 'بلّغوني عند الإطلاق',

  // For Players
  'players.eyebrow': 'للاعبين',
  'players.title': 'لقى شِلّتك. لقى بطولتك. وانزل اللعب.',
  'players.sub': 'كيك أوف يحط كرة الهواة في جيبك — فريقك ومبارياتك وإحصائياتك.',
  'players.f.1.title': 'سوّ ملفك الشخصي',
  'players.f.1.body': 'الاسم وتاريخ الميلاد والمركز (حارس، دفاع، وسط، هجوم) ورقم القميص والمدينة وصورة شخصية.',
  'players.f.2.title': 'كوّن فريق أو انضم لواحد',
  'players.f.2.body': 'ابدأ فريقك مع شعار وألوان، أو انضم بدعوة أو برمز انضمام أو من خلال البحث في الفِرَق العامة.',
  'players.f.3.title': 'أدوات الكابتن',
  'players.f.3.body': 'أدِر القائمة، جدّد رمز الانضمام، عيّن نائب كابتن، خلّ الفريق عام أو خاص، وسجّل في البطولات.',
  'players.f.4.title': 'تابع البطولة',
  'players.f.4.body': 'ترتيب المجموعات، المباريات القادمة، جدول خروج المغلوب، ولوحة بطل بعد ما تخلص البطولة.',
  'players.f.5.title': 'إحصائيات المسيرة',
  'players.f.5.body': 'المباريات والأهداف والتمريرات الحاسمة والبطاقات الصفراء والحمراء والبطولات الملعوبة والمفوز فيها.',
  'players.f.6.title': 'إشعارات فورية',
  'players.f.6.body': 'دعوات وتذكيرات بالمباريات ونتائج — كلّها تجيك على جوّالك.',

  // For Organisers
  'organisers.eyebrow': 'للمنظّمين',
  'organisers.title': 'دير بطولة بثمانية فِرَق بدون ولا جدول إكسل.',
  'organisers.sub': 'من التسجيل إلى صافرة النهاية، كيك أوف يتكفّل بكل الترتيب وأنت تركّز على اليوم نفسه.',
  'organisers.step.1.title': 'الخطوة 1 — التعريف',
  'organisers.step.1.body': 'اسم البطولة والمدينة وحجم القائمة (6–11) وعرضها بشكل عام أو خاص، مع وصف وصورة غلاف اختيارية.',
  'organisers.step.2.title': 'الخطوة 2 — المكان والوقت',
  'organisers.step.2.body': 'الملعب وقائمة المباري مع تحديد ملعب النهائي، الفترات الزمنية كل 30 دقيقة بين 6 صباحًا و11:30 ليلًا، وتواريخ أول مباراة ونصف النهائي والنهائي.',
  'organisers.step.3.title': 'الخطوة 3 — الرسوم والمراجعة',
  'organisers.step.3.body': 'رسوم الاشتراك بالريال السعودي (الافتراضي 1,500)، تاريخ انتهاء التسجيل المقترح تلقائيًا، ومراجعة نهائية.',
  'organisers.during.title': 'يوم المباراة',
  'organisers.during.1': 'اقبل أو ارفض تسجيل الفِرَق عند وصولها.',
  'organisers.during.2': 'ولّد الجدول بضغطة — السيرفر يبني البطولة.',
  'organisers.during.3': 'افتح أي مباراة لإدخال النتيجة أو تعيين حكم أو إعادة جدولتها.',
  'organisers.during.4': 'سجّل الأهداف والتمريرات الحاسمة والإنذارات والضربات الترجيحية في الأدوار الإقصائية.',
  'organisers.during.5': 'أدِر الإيقافات — مباراتين بشكل افتراضي، أو ارفعها لإيقاف البطولة كلّها أو إيقاف دائم.',
  'organisers.during.6': 'سوّ مباريات سريعة — وديّات لمرة واحدة بنفس نموذج النتيجة.',
  'organisers.payments.title': 'الدفع والاسترجاع',
  'organisers.payments.body': 'رسوم الاشتراك تُحصّل بالريال عبر ميسر — كيك أوف ليس التاجر المسجّل. إذا ألغيت البطولة، يحاول كيك أوف استرجاع كل التسجيلات المدفوعة. اللي يفشل استرجاعه يدخل حالة "استرجاع معلّق" للمراجعة.',

  // For Referees
  'referees.eyebrow': 'للحكّام',
  'referees.title': 'مبارياتك. شاشة واحدة. أرسل وخلصت.',
  'referees.sub': 'كيك أوف يعطيك لوحة مركّزة فيها كل اللي تحتاجه يوم المباراة.',
  'referees.f.1.title': 'اليوم وهذا الأسبوع وغير مجدول',
  'referees.f.1.body': 'المباريات المخصّصة لك مرتّبة بحسب التاريخ — أي مباراة بدون موعد بداية تطلع فوق.',
  'referees.f.2.title': 'افتح المباراة وأرسل النتيجة',
  'referees.f.2.body': 'نفس النموذج اللي يستخدمه المنظّم: نتيجة الفريقين، الهدّافين، التمريرات الحاسمة الاختيارية، الإنذارات، والضربات الترجيحية في الأدوار الإقصائية.',
  'referees.f.3.title': 'الترتيب يتحدّث مباشرة',
  'referees.f.3.body': 'لحظة ما ترسل، يتحدّث ترتيب المجموعات وجدول خروج المغلوب لكل المتّصلين.',

  // Features
  'features.eyebrow': 'المميزات',
  'features.title': 'كل اللي يسوّيه كيك أوف اليوم.',
  'features.sub': 'قائمة بالحقائق — بدون وعود قادمة، بدون "قريبًا".',
  'features.cat.tournaments': 'البطولات',
  'features.cat.teams': 'الفِرَق',
  'features.cat.matches': 'المباريات والنتائج',
  'features.cat.accounts': 'الحسابات',
  'features.cat.platform': 'المنصّة',

  // Pricing
  'pricing.eyebrow': 'الأسعار',
  'pricing.title': 'مجاني للاعبين. المنظّم يحدّد الرسوم.',
  'pricing.sub': 'كيك أوف نفسه مجاني للتحميل والاستخدام. كل منظّم يحدّد رسوم الاشتراك لكل بطولة.',
  'pricing.players.title': 'اللاعبون',
  'pricing.players.price': 'مجاني',
  'pricing.players.body': 'حمّل التطبيق، سوّ ملفك، انضم لفريق أو كوّن واحد، وسجّل في البطولات. بدون اشتراك، بدون عملات داخلية.',
  'pricing.players.bullet.1': 'فِرَق بلا حدّ في أدوار مختلفة',
  'pricing.players.bullet.2': 'إحصائيات مسيرتك وتاريخ بطولاتك',
  'pricing.players.bullet.3': 'إشعارات الدعوات والمباريات',
  'pricing.organisers.title': 'المنظّمون',
  'pricing.organisers.price': 'أنت تحدّد',
  'pricing.organisers.body': 'حدّد رسوم الاشتراك بالريال السعودي عند إنشاء البطولة (الافتراضي 1,500 ريال). الدفع يتم بالريال عبر ميسر — كيك أوف ليس التاجر المسجّل لرسوم الاشتراك.',
  'pricing.organisers.bullet.1': 'بطولات بثمانية فِرَق وجدول يتعبّى تلقائيًا',
  'pricing.organisers.bullet.2': 'قبول التسجيلات وآلية الاسترجاع',
  'pricing.organisers.bullet.3': 'إدخال النتائج والإيقافات والمباريات السريعة',
  'pricing.note': 'الاسترجاع يدير المنظّم عبر ميسر. كيك أوف يبدأ محاولة الاسترجاع عند الإلغاء لكن لا يضمنها.',

  // Download
  'download.eyebrow': 'تحميل',
  'download.title': 'قريبًا على iOS و Android.',
  'download.sub': 'نشتغل على آخر اللمسات قبل نزول التطبيق على App Store و Google Play. اترك إيميلك ونبلّغك أوّل ما ينزل.',
  'download.cta': 'راسلنا على support@kickoffsa.com',
  'download.ios.title': 'iOS',
  'download.ios.body': 'متجر آبل · قريبًا',
  'download.android.title': 'Android',
  'download.android.body': 'متجر جوجل بلاي · قريبًا',

  // Contact
  'contact.eyebrow': 'تواصل',
  'contact.title': 'تعال نتكلم كرة.',
  'contact.sub': 'أي سؤال أو ملاحظة أو بطولة تبي تنظّمها؟ تواصل معنا.',
  'contact.support.title': 'الدعم',
  'contact.support.body': 'لأي مساعدة بالحساب أو الدفع أو غيره.',
  'contact.support.cta': 'support@kickoffsa.com',
  'contact.legal.title': 'الكيان القانوني',
  'contact.legal.body': 'كيك أوف تكنولوجيز · المملكة العربية السعودية · الاختصاص: محاكم الرياض.',

  // 404
  '404.title': 'خارج الملعب.',
  '404.sub': 'الصفحة مو موجودة. نرجّعك للأكشن.',
  '404.cta': 'الرئيسية',

  // Privacy / Terms
  'privacy.eyebrow': 'الخصوصية',
  'privacy.title': 'سياسة الخصوصية',
  'privacy.updated': 'آخر تحديث: مايو 2026',
  'terms.eyebrow': 'الشروط',
  'terms.title': 'شروط الخدمة',
  'terms.updated': 'آخر تحديث: مايو 2026',
};

export const strings: Record<'en' | 'ar', Dict> = { en, ar };
